name: Build / Studios

on:
  push:
    # On Push to Master branch
    branches: 
      - master
    # Ignore all Tags / Release
    tags-ignore:
      - '**'
    paths:
      - '**.mpe1'

  workflow_call:
    outputs:
      version:
        description: "MPE1 Version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Studios / Version
    runs-on: windows-2019
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Git Checkout / MPE / XPath / Tools
        uses: actions/checkout@v4
        with:
          repository: andrewjswan/MPE
          path: MPE

      - name: Get Version
        if: ${{ success() }}
        id: version
        run: |
          FOR /F "tokens=*" %%i IN ('call ..\MPE\XPath\xpath.cmd "mediaportal.studios.xmp2" "//PackageClass/GeneralInfo/Version" ^| ..\MPE\Tools\sed "s/ /./g"') DO (ECHO version=%%i >> %GITHUB_OUTPUT%)
        working-directory: ${{ github.workspace }}\script
        shell: cmd

  release:
    name: Studios / Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Studios v${{ needs.build.outputs.version }}
          tag_name: v${{ needs.build.outputs.version }}
          generate_release_notes: true

  ci-status:
    name: Release Status
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
